# Generated by Django 3.2.9 on 2021-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_ratingrooms_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарий'),
        ),
    ]
