# Generated by Django 3.2.9 on 2021-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_bookingroom_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Фото'),
        ),
    ]
