# Generated by Django 3.2.9 on 2021-11-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booking/', verbose_name='Фото'),
        ),
    ]
